### ISSUE TITLE
would it be hard to add k<31 support for .ctx files?

### ISSUE THREAD

**Issue by iqbal-lab** [bingmann/cobs#14]
I know @graceblackwell is interested in k=19

**Comment by bingmann** [comment]
Okay, should not be a problem. Could you please send me a small (few KiB) .ctx with k=19, which I can include in the tests.

**Comment by bingmann** [comment]
done. soon in master branch.

**Comment by iqbal-lab** [comment]
Just back from holiday! i assume some small datasets still useful?

**Comment by bingmann** [comment]
naw. all done. made some myself.
