### ISSUE TITLE
Fail during make -j4 (GCC8 is used)

### ISSUE THREAD

**Issue by MinghaoYan** [bingmann/cobs#7]
Hi! I'm using GCC8 for compilation and my CMake output is 
> -- COBS CMAKE_CXX_FLAGS: -Wpedantic -W -Wall -march=native -fPIC
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- TLX CMAKE_CXX_FLAGS: -Wshadow -Wold-style-cast -std=c++17 -g -W -Wall -Wextra -fPIC  -Wpedantic -W -Wall -march=native -fPIC -Wcast-qual -Winit-self -Wnoexcept -Woverloaded-virtual -Wredundant-decls
-- pybind11 v2.4.3
-- Configuring done
-- Generating done
-- Build files have been written to: /scratch/my29/cobs/build

When I run make -j4 I would get the following error, it would drag on for thousands of more lines, here is an excerpt of the beginning of the error messages

> Scanning dependencies of target gtest
Scanning dependencies of target xxhash
Scanning dependencies of target tlx
[  1%] Building C object extlib/xxhash/cmake_unofficial/CMakeFiles/xxhash.dir/__/xxhash.c.o
[  2%] Linking C static library libxxhash.a
[  2%] Built target xxhash
Scanning dependencies of target xxhsum
[  3%] Building C object extlib/xxhash/cmake_unofficial/CMakeFiles/xxhsum.dir/__/xxhsum.c.o
[  4%] Building CXX object extlib/googletest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  6%] Building CXX object extlib/tlx/tlx/CMakeFiles/tlx.dir/backtrace.cpp.o
[  6%] Building CXX object extlib/tlx/tlx/CMakeFiles/tlx.dir/algorithm/parallel_multiway_merge.cpp.o
[  7%] Linking C executable xxhsum
[  7%] Built target xxhsum
[  8%] Building CXX object extlib/tlx/tlx/CMakeFiles/tlx.dir/cmdline_parser.cpp.o
/tmp/ccMLvSpN.s: Assembler messages:
/tmp/ccMLvSpN.s:15: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:15: Error: junk at end of line, first unrecognized character is `-'
/tmp/ccMLvSpN.s:17: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:17: Error: unknown pseudo-op: `.lvu1'
/tmp/ccMLvSpN.s:18: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:18: Error: unknown pseudo-op: `.lvu2'
/tmp/ccMLvSpN.s:19: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:19: Error: unknown pseudo-op: `.lvu3'
/tmp/ccMLvSpN.s:20: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:20: Error: unknown pseudo-op: `.lvu4'
/tmp/ccMLvSpN.s:21: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:21: Error: unknown pseudo-op: `.lvu5'
/tmp/ccMLvSpN.s:25: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:25: Error: unknown pseudo-op: `.lvu6'
/tmp/ccMLvSpN.s:27: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:27: Error: unknown pseudo-op: `.lvu7'
/tmp/ccMLvSpN.s:33: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:33: Error: unknown pseudo-op: `.lvu8'
/tmp/ccMLvSpN.s:37: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:37: Error: unknown pseudo-op: `.lvu9'
/tmp/ccMLvSpN.s:40: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:40: Error: unknown pseudo-op: `.lvu10'
/tmp/ccMLvSpN.s:44: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:44: Error: unknown pseudo-op: `.lvu11'
/tmp/ccMLvSpN.s:47: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:47: Error: unknown pseudo-op: `.lvu12'
/tmp/ccMLvSpN.s:48: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:48: Error: unknown pseudo-op: `.lvu13'
/tmp/ccMLvSpN.s:51: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:51: Error: unknown pseudo-op: `.lvu14'
/tmp/ccMLvSpN.s:55: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:55: Error: unknown pseudo-op: `.lvu15'
/tmp/ccMLvSpN.s:56: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:56: Error: unknown pseudo-op: `.lvu16'
/tmp/ccMLvSpN.s:59: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:59: Error: unknown pseudo-op: `.lvu17'
/tmp/ccMLvSpN.s:61: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:61: Error: unknown pseudo-op: `.lvu18'
/tmp/ccMLvSpN.s:64: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:64: Error: unknown pseudo-op: `.lvu19'
/tmp/ccMLvSpN.s:65: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:65: Error: unknown pseudo-op: `.lvu20'
/tmp/ccMLvSpN.s:84: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:84: Error: junk at end of line, first unrecognized character is `-'
/tmp/ccMLvSpN.s:86: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:86: Error: unknown pseudo-op: `.lvu22'
/tmp/ccMLvSpN.s:119: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:119: Error: unknown pseudo-op: `.lvu23'
/tmp/ccMLvSpN.s:120: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:120: Error: unknown pseudo-op: `.lvu24'
/tmp/ccMLvSpN.s:122: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:122: Error: unknown pseudo-op: `.lvu25'
/tmp/ccMLvSpN.s:123: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:123: Error: unknown pseudo-op: `.lvu26'
/tmp/ccMLvSpN.s:125: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:125: Error: unknown pseudo-op: `.lvu27'
/tmp/ccMLvSpN.s:128: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:128: Error: unknown pseudo-op: `.lvu28'
/tmp/ccMLvSpN.s:130: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:130: Error: unknown pseudo-op: `.lvu29'
/tmp/ccMLvSpN.s:132: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:132: Error: unknown pseudo-op: `.lvu30'
/tmp/ccMLvSpN.s:134: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:134: Error: unknown pseudo-op: `.lvu31'
/tmp/ccMLvSpN.s:138: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:138: Error: unknown pseudo-op: `.lvu32'
/tmp/ccMLvSpN.s:142: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:142: Error: unknown pseudo-op: `.lvu33'
/tmp/ccMLvSpN.s:144: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:144: Error: unknown pseudo-op: `.lvu34'
/tmp/ccMLvSpN.s:145: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:145: Error: unknown pseudo-op: `.lvu35'
/tmp/ccMLvSpN.s:148: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:148: Error: unknown pseudo-op: `.lvu36'
/tmp/ccMLvSpN.s:150: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:150: Error: unknown pseudo-op: `.lvu37'
/tmp/ccMLvSpN.s:153: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:153: Error: unknown pseudo-op: `.lvu38'
/tmp/ccMLvSpN.s:154: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:154: Error: unknown pseudo-op: `.lvu39'
/tmp/ccMLvSpN.s:163: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:163: Error: unknown pseudo-op: `.lvu40'
/tmp/ccMLvSpN.s:164: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:164: Error: unknown pseudo-op: `.lvu41'
/tmp/ccMLvSpN.s:169: Error: unknown .loc sub-directive `view'
/tmp/ccMLvSpN.s:169: Error: unknown pseudo-op: `.lvu42'
/tmp/ccMLvSpN.s:172: Error: unknown .loc sub-directive `view'

How should I fix this? Thank you very much!

**Comment by bingmann** [comment]
Sorry, no idea. This is a very strange error by the assembler that should never occur.
I think your whole compiler setup may be broken.
